### ISSUE TITLE
Running `npm run main` for the deployment of display-client has an error

### ISSUE THREAD

**Issue by cunwow** [googlemaps/transport-tracker#14]
Hello!
When I follow  https://developers.google.com/maps/solutions/transport-tracker/start  to the fifth step. 
I am running `npm run main` for the deployment of display-client but there was an error.
system: Ubuntu 16.04.2 LTS ;
```
> display-client@1.0.0 main /home/nick/transport-tracker-map
> gulp serve

[11:43:47] Using gulpfile /home/nick/transport-tracker-map/gulpfile.js
[11:43:47] Starting 'less-compile'...
[11:43:47] Finished 'less-compile' after 114 ms
[11:43:47] Starting 'serve'...
[11:43:47] Finished 'serve' after 3.63 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL ::1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! display-client@1.0.0 main: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the display-client@1.0.0 main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-05-23T03_43_47_693Z-debug.log
```

2017-05-23T03_43_47_693Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/node-v6.9.5-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'main' ]
2 info using npm@4.6.1
3 info using node@v6.9.5
4 verbose run-script [ 'premain', 'main', 'postmain' ]
5 info lifecycle display-client@1.0.0~premain: display-client@1.0.0
6 silly lifecycle display-client@1.0.0~premain: no script for premain, continuing
7 info lifecycle display-client@1.0.0~main: display-client@1.0.0
8 verbose lifecycle display-client@1.0.0~main: unsafe-perm in lifecycle true
9 verbose lifecycle display-client@1.0.0~main: PATH: /root/node-v6.9.5-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/home/nick/transport-tracker-map/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle display-client@1.0.0~main: CWD: /home/nick/transport-tracker-map
11 silly lifecycle display-client@1.0.0~main: Args: [ '-c', 'gulp serve' ]
12 silly lifecycle display-client@1.0.0~main: Returned: code: 1  signal: null
13 info lifecycle display-client@1.0.0~main: Failed to exec main script
14 verbose stack Error: display-client@1.0.0 main: `gulp serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/node-v6.9.5-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/node-v6.9.5-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid display-client@1.0.0
16 verbose cwd /home/nick/transport-tracker-map
17 verbose Linux 4.4.0-63-generic
18 verbose argv "/root/node-v6.9.5-linux-x64/bin/node" "/usr/local/bin/npm" "run" "main"
19 verbose node v6.9.5
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error display-client@1.0.0 main: `gulp serve`
23 error Exit status 1
24 error Failed at the display-client@1.0.0 main script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by AnnabellGhost** [comment]
error occurs in `main.js` have you check that out?
and elifecycle is a node error which caused by unexpectedly  cease
thats all I can help ....

**Comment by domesticmouse** [comment]
I'm guessing you are attempting to run this code: https://github.com/googlemaps/transport-tracker/tree/master/display-client

The trick here is that the failing `gulp serve` is nothing to do with the codebase linked above, it's just a web server. The npm generated stack trace is pointing out that it is failing to find a port on which to serve the HTML and JS content. 

As a work around, this content can be served from any web server, so I'd suggest you try running something like `python -m SimpleHTTPServer 8000`. Thanks!

**Comment by mikebernal** [comment]
@domesticmouse  how can do that in my gulpfile? 
what should I change here? Thanks
serve({
    root: ['.'],
    port: 8080
  }) 
I am running the code through Google cloud . Thanks
