### ISSUE TITLE
Error: Cannot find module './paths.json'

### ISSUE THREAD

**Issue by ghzoan** [googlemaps/transport-tracker#35]
1 week trying installing google map, and the map not showing at all

finally im using now google cloud shell its must be without error

but in backend installing process go this
npm ERR! transport-tracker-server@1.0.0 main: node main.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the transport-tracker-server@1.0.0 main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

and in map process the process stuck

i think there something wrong with this I tried all the steps many times and many alternative link, just this one not working with me the others showing the map

please any help!

www.gps.jernascenter.com in this link you will see the third test how its not showing the map and admin panel also

**Comment by quarky912** [comment]
if you are working on cloud shell then if possible please allow me to contribute to your project. I have successfully built the simulator for New Delhi map, India. @ghzoan

**Comment by ghzoan** [comment]
@quarky912

Yes please or we can meet by Team viewer, 
Or how to contribute?

**Comment by domesticmouse** [comment]
Please review the codelab that talks through how to use this code:
https://codelabs.developers.google.com/codelabs/transport-tracker-backend/

**Comment by naeemjawaid** [comment]
Updating npm worked for me.

**Comment by ideaLabs21** [comment]
https://raw.githubusercontent.com/googlecodelabs/transport-tracker-codelab/master/backend/step-08/paths.json

**Comment by Hager777** [comment]
@lakshaykakkarr 
Please help me to solve this error, i am in step_6 in Transport Tracker Backend
 https://codelabs.developers.google.com/codelabs/transport-tracker-backend/

Error: Cannot find module 'asyncawait/async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/hagarsalh777/transport-tracker-server/time_table.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/hagarsalh777/transport-tracker-server/main.js:25:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
