### ISSUE TITLE
Error while running backend

### ISSUE THREAD

**Issue by monikagupta78** [googlemaps/transport-tracker#49]
I am setting up backend, after running npm run main I am getting below error:

at Array.map (<anonymous>)
    at _await.panelConfig.map.panel (D:\projects\transport-tracker\backend\time_table.js:61:35)
    at Array.map (<anonymous>)
    at exports.TimeTable.publishTimeTables (D:\projects\transport-tracker\backend\time_table.js:58:24)
    at _async (D:\projects\transport-tracker\backend\time_table.js:45:16)
    at tryBlock (D:\projects\transport-tracker\backend\node_modules\asyncawait\src\async\fiberManager.js:39:33)
    at runInFiber (D:\projects\transport-tracker\backend\node_modules\asyncawait\src\async\fiberManager.js:26:9)
TypeError: Cannot read property 'legs' of undefined
    at exports.TimeTable.tripsLookup (D:\projects\transport-tracker\backend\time_table.js:122:23)
    at left.panel.routesGroups.(anonymous function).map.route_id (D:\projects\transport-tracker\backend\time_table.js:62

Pls help

**Comment by hynra** [comment]
See my answer here https://github.com/googlemaps/transport-tracker/issues/48#issuecomment-415019765
