### ISSUE TITLE
Can not launch backhend "npm install" transport tracker

### ISSUE THREAD

**Issue by Dr-Lemon** [googlemaps/transport-tracker#61]
Hello,

I have a big mistake throwing the npm run hand.

First of all I run an install npm with the current version of node and npm and here are the errors I had:

```
root@**********:/var/www/html/backend# npm install
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

> sqlite3@3.1.13 install /var/www/html/backend/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@11.12.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@11.12.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/var/www/html/backend/node_modules/sqlite3/build'
make: Entering directory '/var/www/html/backend/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  TOUCH Release/obj.target/deps/action_before_build.stamp
Release/obj.target/deps/action_before_build.stamp Stats {
  dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 794068,
  size: 0,
  blocks: 0,
  atimeMs: 1553161469000,
  mtimeMs: 1553161469000,
  ctimeMs: 1553161469860,
  birthtimeMs: 1553161469860,
  atime: 2019-03-21T09:44:29.000Z,
  mtime: 2019-03-21T09:44:29.000Z,
  ctime: 2019-03-21T09:44:29.860Z,
  birthtime: 2019-03-21T09:44:29.860Z }
Release/obj.target/deps/action_before_build.stamp Stats {
  dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 794068,
  size: 0,
  blocks: 0,
  atimeMs: 1553161469000,
  mtimeMs: 1553161469000,
  ctimeMs: 1553161469864,
  birthtimeMs: 1553161469864,
  atime: 2019-03-21T09:44:29.000Z,
  mtime: 2019-03-21T09:44:29.000Z,
  ctime: 2019-03-21T09:44:29.864Z,
  birthtime: 2019-03-21T09:44:29.864Z }
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw Stats {
  dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 922088,
  size: 119,
  blocks: 8,
  atimeMs: 1553161563000,
  mtimeMs: 1553161563000,
  ctimeMs: 1553161563816,
  birthtimeMs: 1553161563816,
  atime: 2019-03-21T09:46:03.000Z,
  mtime: 2019-03-21T09:46:03.000Z,
  ctime: 2019-03-21T09:46:03.816Z,
  birthtime: 2019-03-21T09:46:03.816Z }
./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw Stats {
  dev: 2049,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 922088,
  size: 119,
  blocks: 8,
  atimeMs: 1553161563000,
  mtimeMs: 1553161563000,
  ctimeMs: 1553161563824,
  birthtimeMs: 1553161563824,
  atime: 2019-03-21T09:46:03.000Z,
  mtime: 2019-03-21T09:46:03.000Z,
  ctime: 2019-03-21T09:46:03.824Z,
  birthtime: 2019-03-21T09:46:03.824Z }
sed: can't read ./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw: No such file or directory
  AR(target) Release/obj.target/deps/sqlite3.a
rm: cannot remove './Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw': No such file or directory
deps/sqlite3.target.mk:129: recipe for target 'Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o' failed
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Error 1
make: Leaving directory '/var/www/html/backend/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64"
gyp ERR! cwd /var/www/html/backend/node_modules/sqlite3
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/html/backend/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:988:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 3.16.0-7-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/var/www/html/backend/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/html/backend/node_modules/sqlite3
node-pre-gyp ERR! node -v v11.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64' (1)
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.h:10:0,e sqlite3@3.1.13~install: Failed to exec install script
                 from ../src/database.cc:4:
../../nan/nan.h:148:53: fatal error: nan_callbacks.h: No such file or directory
compilation terminated.
Cannot create temporary file in /var/www/html/backend/node_modules/sqlite3/: No such file or directory
node_sqlite3.target.mk:121: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Aborted
make: Leaving directory '/var/www/html/backend/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/www/html/backend/node_modules/sqlite3/lib/binding/node-v67-linux-x64"
gyp ERR! cwd /var/www/html/backend/node_modules/sqlite3
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-21T09_46_04_812Z-debug.log

```

Then I'm moving to a version of node in 6.17.0
The installation of dependencies is very good but at the time of launching "npm run main" here are my mistakes:

```
> transport-tracker-server@1.0.0 main /var/www/html/backend
> node main.js

module.js:478
    throw err;
    ^

Error: Cannot find module './heart_beat.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/backend/main.js:41:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! transport-tracker-server@1.0.0 main: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the transport-tracker-server@1.0.0 main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-21T09_22_45_755Z-debug.log

```

I wanted to know if someone had solved the problems?
What do you need as a prerequisite to start the backhend?

**Comment by Mo9a7i** [comment]
just update packages.json sqlite line to version 3.1.9

but that wouldn't be the end of problems with this repo, you wouldn't be able to achieve the end of tutorial with a running product, unfortunately it's garbage that's still kept online.

**Comment by rohit421991** [comment]
True, its a garbage only.
